env:
  commonjs: true
  es6: true
  node: true
  "jest/globals": true
extends: "eslint:recommended"
plugins:
  - jest
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2019
rules:
  comma-dangle: [2, always-multiline]
  no-unused-vars: error
