extends:
  - react-app
  - plugin:import/errors
  - plugin:import/warnings

rules:
  comma-dangle: [2, always-multiline]
  jsx-a11y/anchor-is-valid: 0
  no-unused-vars:
    - error
    - ignoreRestSiblings: true

  import/no-named-as-default: 0
